"""
Data models for NovaFlow Data Access Control.

This module defines the core data structures used throughout the
access control subsystem.
"""

from dataclasses import dataclass, field
from typing import List
from enum import Enum


class UCPrivilege(Enum):
    """
    Unity Catalog table-level privileges.
    
    These are the privileges that NovaFlow manages at the table level.
    Schema and catalog-level privileges are managed by the platform team.
    """
    SELECT = "SELECT"
    MODIFY = "MODIFY"
    ALL_PRIVILEGES = "ALL PRIVILEGES"


@dataclass
class PrivilegeIntent:
    """
    INTENDED privilege state (what SHOULD exist).
    
    Calculated from access metadata (roles + mappings).
    Represents the desired privilege assignment.
    
    Attributes:
        table: Fully qualified table name (catalog.schema.table)
        ad_group: AD group name
        privilege: Privilege to grant
        reason: Why this privilege should exist (e.g., "Role: consumer.payments")
    
    Example:
        PrivilegeIntent(
            table="catalog.schema.payment_table1",
            ad_group="ad_grp_payments_team_dev",
            privilege=UCPrivilege.SELECT,
            reason="Role: consumer.payments (inherits consumer)"
        )
    """
    table: str
    ad_group: str
    privilege: UCPrivilege
    reason: str
    role_name: str = ""

    def __post_init__(self):
        """Convert string privilege to enum if needed."""
        if isinstance(self.privilege, str):
            self.privilege = UCPrivilege(self.privilege)
    
    def __hash__(self):
        """Make hashable for set operations."""
        return hash((self.table, self.ad_group, self.privilege))
    
    def __eq__(self, other):
        """
        Enable equality comparison.

        Can compare with ActualPrivilege - only compares key fields
        (table, ad_group, privilege), ignoring reason field.
        """
        if not isinstance(other, (PrivilegeIntent, ActualPrivilege)):
            return False
        return (
            self.table == other.table and
            self.ad_group == other.ad_group and
            self.privilege == other.privilege
        )


@dataclass
class ActualPrivilege:
    """
    ACTUAL privilege state (what IS in Unity Catalog).
    
    Queried from UC using SHOW GRANTS.
    Represents the current privilege assignment.
    
    Attributes:
        table: Fully qualified table name (catalog.schema.table)
        ad_group: AD group name
        privilege: Privilege currently granted
    
    Example:
        ActualPrivilege(
            table="catalog.schema.payment_table1",
            ad_group="ad_grp_payments_team_dev",
            privilege=UCPrivilege.SELECT
        )
    """
    table: str
    ad_group: str
    privilege: UCPrivilege
    
    def __post_init__(self):
        """Convert string privilege to enum if needed."""
        if isinstance(self.privilege, str):
            self.privilege = UCPrivilege(self.privilege)
    
    def __hash__(self):
        """Make hashable for set operations."""
        return hash((self.table, self.ad_group, self.privilege))
    
    def __eq__(self, other):
        """
        Enable equality comparison.

        Can compare with PrivilegeIntent - only compares key fields
        (table, ad_group, privilege).
        """
        if not isinstance(other, (PrivilegeIntent, ActualPrivilege)):
            return False
        return (
            self.table == other.table and
            self.ad_group == other.ad_group and
            self.privilege == other.privilege
        )


@dataclass
class PrivilegeDelta:
    """
    CHANGE needed (GRANT or REVOKE).
    
    Represents the difference between intended and actual state.
    Generated by comparing PrivilegeIntent vs ActualPrivilege.
    
    Attributes:
        action: "GRANT" or "REVOKE"
        table: Fully qualified table name
        ad_group: AD group name
        privilege: Privilege to grant or revoke
        reason: Why this change is needed
    
    Examples:
        # Need to grant (in intent but not actual)
        PrivilegeDelta(
            action="GRANT",
            table="catalog.schema.payment_table1",
            ad_group="ad_grp_payments_team_dev",
            privilege=UCPrivilege.SELECT,
            reason="Role: consumer.payments"
        )
        
        # Need to revoke (in actual but not intent)
        PrivilegeDelta(
            action="REVOKE",
            table="catalog.schema.payment_table1",
            ad_group="ad_grp_old_team_dev",
            privilege=UCPrivilege.SELECT,
            reason="Not in current metadata - removing"
        )
    """
    action: str  # "GRANT" or "REVOKE"
    table: str
    ad_group: str
    privilege: UCPrivilege
    reason: str
    
    def __post_init__(self):
        """Validate and normalize data."""
        if isinstance(self.privilege, str):
            self.privilege = UCPrivilege(self.privilege)
        
        if self.action not in ("GRANT", "REVOKE"):
            raise ValueError(f"Invalid action: {self.action}. Must be GRANT or REVOKE")
    
    @property
    def sql(self) -> str:
        """
        Generate SQL statement for this delta.
        
        Returns:
            GRANT or REVOKE SQL statement
        
        Examples:
            GRANT SELECT ON TABLE catalog.schema.table TO `ad_group`
            REVOKE SELECT ON TABLE catalog.schema.table FROM `ad_group`
        """
        if self.action == "GRANT":
            return (
                f"GRANT {self.privilege.value} "
                f"ON TABLE {self.table} "
                f"TO `{self.ad_group}`"
            )
        else:  # REVOKE
            return (
                f"REVOKE {self.privilege.value} "
                f"ON TABLE {self.table} "
                f"FROM `{self.ad_group}`"
            )


@dataclass
class AccessControlResult:
    """
    Result of applying access control to a table.
    
    Tracks what was intended, what was actual, what changes were made,
    and whether those changes succeeded.
    
    Attributes:
        table: Fully qualified table name
        intended_count: Number of intended privileges
        actual_count: Number of actual privileges (before changes)
        grants_attempted: Number of GRANTs attempted
        grants_succeeded: Number of GRANTs that succeeded
        grants_failed: Number of GRANTs that failed
        revokes_attempted: Number of REVOKEs attempted
        revokes_succeeded: Number of REVOKEs that succeeded
        revokes_failed: Number of REVOKEs that failed
        no_change_count: Number of privileges already correct
        execution_time_seconds: Time taken to execute changes
        errors: List of error messages (if any)
    """
    table: str
    
    # State counts
    intended_count: int
    actual_count: int
    no_change_count: int
    
    # GRANT results
    grants_attempted: int
    grants_succeeded: int
    grants_failed: int
    
    # REVOKE results
    revokes_attempted: int
    revokes_succeeded: int
    revokes_failed: int
    
    # Timing and errors
    execution_time_seconds: float
    errors: List[str] = field(default_factory=list)
    
    @property
    def is_successful(self) -> bool:
        """
        Check if all changes succeeded.
        
        Returns:
            True if no failures and no errors
        """
        return (
            self.grants_failed == 0 and
            self.revokes_failed == 0 and
            len(self.errors) == 0
        )
    
    @property
    def total_changes(self) -> int:
        """
        Total number of changes attempted.
        
        Returns:
            Sum of GRANTs and REVOKEs attempted
        """
        return self.grants_attempted + self.revokes_attempted
    
    @property
    def success_rate(self) -> float:
        """
        Calculate success rate as percentage.
        
        Returns:
            Success rate (0-100)
        """
        if self.total_changes == 0:
            return 100.0
        
        succeeded = self.grants_succeeded + self.revokes_succeeded
        return (succeeded / self.total_changes) * 100.0
    
    def __str__(self) -> str:
        """Human-readable string representation."""
        return (
            f"AccessControlResult(table={self.table}, "
            f"GRANTs={self.grants_succeeded}/{self.grants_attempted}, "
            f"REVOKEs={self.revokes_succeeded}/{self.revokes_attempted}, "
            f"Success={self.success_rate:.1f}%)"
        )