---
# ════════════════════════════════════════════════════════════════════════════
# CONCRETE EXAMPLE: Product Sales Summary Data Contract
# ════════════════════════════════════════════════════════════════════════════
#
# FILE: samples/transformation_examples/EXAMPLE_product_sales_summary.yaml
#
# This data contract corresponds to:
#   transformations/python/product_sales_summary_example.py
#
# PURPOSE: Complete working example showing how to configure a transformation
#
# ════════════════════════════════════════════════════════════════════════════

apiVersion: v3.0.2
kind: DataContract
name: product_sales_summary_example
version: "1.0.0"

# ────────────────────────────────────────────────────────────────────────────
# Metadata
# ────────────────────────────────────────────────────────────────────────────
domain: sales
dataProduct: product_analytics

team:
  dataOwner: sales-analytics-team@example.com
  seniorManager: vp-sales@example.com
  dataSteward: data-steward@example.com

# ────────────────────────────────────────────────────────────────────────────
# Output Schema Definition
# ────────────────────────────────────────────────────────────────────────────
# Define what your transformation will produce
# ────────────────────────────────────────────────────────────────────────────
schema:
  # Where the data will be written
  name: gold_sales.product_sales_summary_example
  table: product_sales_summary_example
  format: delta
  description: Product sales summary with metrics and tier classification

  # Output columns that your transformation produces
  properties:
    - name: product_id
      type: bigint
      description: Unique product identifier
      isPrimaryKey: true
      isNullable: false

    - name: total_orders
      type: bigint
      description: Total number of orders for this product
      isNullable: false

    - name: total_revenue
      type: decimal(18,2)
      description: Total revenue generated by this product
      isNullable: false

    - name: avg_order_value
      type: decimal(18,2)
      description: Average order value for this product
      isNullable: false

    - name: first_order_date
      type: date
      description: Date of first order for this product
      isNullable: true

    - name: last_order_date
      type: date
      description: Date of most recent order for this product
      isNullable: true

    - name: unique_customers
      type: bigint
      description: Number of unique customers who ordered this product
      isNullable: false

    - name: revenue_tier
      type: string
      description: Revenue classification (High, Medium, Low)
      isNullable: false

    - name: revenue_per_customer
      type: decimal(18,2)
      description: Average revenue per unique customer
      isNullable: false

    - name: days_active
      type: integer
      description: Number of days between first and last order
      isNullable: true

# ────────────────────────────────────────────────────────────────────────────
# Transformation Configuration
# ────────────────────────────────────────────────────────────────────────────
# This is where you configure YOUR transformation
# ────────────────────────────────────────────────────────────────────────────
customProperties:
  # Pipeline configuration
  pipelineType: transformation
  writeStrategy: overwrite
  softDelete: false

  # ══════════════════════════════════════════════════════════════════════════
  # TRANSFORMATION SPECIFICATION
  # ══════════════════════════════════════════════════════════════════════════
  # Tell framework which transformation to use
  # ══════════════════════════════════════════════════════════════════════════

  # Transformation type (python, sql, or scala)
  transformationType: python

  # Your Python file name (without .py extension)
  # Framework will look for: transformations/python/product_sales_summary_example.py
  transformationModule: product_sales_summary_example

  # Your class name (inside the Python file)
  # Framework will instantiate: ProductSalesSummaryExample(spark)
  transformationClass: ProductSalesSummaryExample

  # ══════════════════════════════════════════════════════════════════════════
  # YOUR CONFIGURATION
  # ══════════════════════════════════════════════════════════════════════════
  # This configuration is passed to your run() method as **kwargs
  # Access in your code with: kwargs.get('key_name', default_value)
  # ══════════════════════════════════════════════════════════════════════════

  transformationConfig:
    # Source catalog name
    # Used in code as: kwargs.get('source_catalog', 'bronze')
    source_catalog: bronze

    # Number of days to look back for orders
    # Used in code as: kwargs.get('lookback_days', 30)
    lookback_days: 30

    # Minimum order amount to include
    # Used in code as: kwargs.get('min_order_amount', 0.0)
    min_order_amount: 10.0

# ────────────────────────────────────────────────────────────────────────────
# Data Quality Rules
# ────────────────────────────────────────────────────────────────────────────
quality:
  validation:
    # Ensure product_id is unique
    - column: product_id
      rule: unique
      severity: error

    # Ensure revenue is non-negative
    - column: total_revenue
      rule: min
      value: 0
      severity: error

    # Ensure order count is positive
    - column: total_orders
      rule: min
      value: 1
      severity: error

    # Ensure revenue tier is valid
    - column: revenue_tier
      rule: allowed_values
      values:
        - High
        - Medium
        - Low
      severity: error

# ════════════════════════════════════════════════════════════════════════════
# NOTES FOR DEVELOPERS:
# ════════════════════════════════════════════════════════════════════════════
#
# 1. Framework reads this file and extracts transformation configuration
# 2. transformationModule → finds your Python file
# 3. transformationClass → finds your class in that file
# 4. transformationConfig → passed to your run() method as **kwargs
# 5. Framework instantiates: YourClass(spark)
# 6. Framework calls: instance.run(input_df, **your_config)
# 7. Framework writes result to: schema.name (gold_sales.product_sales_summary_example)
#
# ════════════════════════════════════════════════════════════════════════════
