---
apiVersion: v3.0.2
kind: DataContract
name: customer_360_view
version: "1.0.0"

domain: sales
dataProduct: customer_analytics

team:
  dataOwner: customer-analytics-team@example.com
  seniorManager: vp-analytics@example.com
  dataSteward: data-steward@example.com

schema:
  name: gold_sales.customer_360_view
  table: customer_360_view
  format: delta
  description: Comprehensive customer 360 view with RFM scoring

  properties:
    - name: customer_id
      type: bigint
      description: Unique customer identifier
      isPrimaryKey: true
      isNullable: false

    - name: customer_name
      type: string
      description: Customer full name
      isNullable: false

    - name: customer_email
      type: string
      description: Customer email address
      isNullable: true

    - name: total_orders
      type: bigint
      description: Total number of orders
      isNullable: false

    - name: total_revenue
      type: decimal(18,2)
      description: Total customer revenue
      isNullable: false

    - name: avg_order_value
      type: decimal(18,2)
      description: Average order value
      isNullable: false

    - name: first_order_date
      type: date
      description: Date of first order
      isNullable: true

    - name: last_order_date
      type: date
      description: Date of most recent order
      isNullable: true

    - name: recency_days
      type: integer
      description: Days since last order
      isNullable: false

    - name: recency_score
      type: integer
      description: RFM recency score (1-4)
      isNullable: false

    - name: frequency_score
      type: integer
      description: RFM frequency score (1-4)
      isNullable: false

    - name: monetary_score
      type: integer
      description: RFM monetary score (1-4)
      isNullable: false

    - name: rfm_score
      type: integer
      description: Composite RFM score
      isNullable: false

    - name: customer_segment
      type: string
      description: Customer segment (Champions, Loyal, At Risk, etc.)
      isNullable: false

    - name: customer_value
      type: string
      description: Customer value tier (High, Medium, Low)
      isNullable: false

customProperties:
  pipelineType: transformation
  writeStrategy: overwrite
  softDelete: false

  # Class-based Python transformation
  transformationType: python
  transformationModule: customer_360_class
  transformationClass: Customer360Transformation

  # Configuration passed to the transformation
  transformationConfig:
    source_catalog: bronze_sales
    lookback_days: 90
    min_order_amount: 10.0

quality:
  validation:
    - column: customer_id
      rule: unique
      severity: error

    - column: rfm_score
      rule: between
      min: 100
      max: 444
      severity: warning

    - column: customer_segment
      rule: allowed_values
      values:
        - Champions
        - Loyal Customers
        - Potential Loyalists
        - At Risk
        - Hibernating
        - Lost
      severity: error
