---
apiVersion: v3.0.2
kind: DataContract
name: customer_orders_summary
version: "1.0.0"

domain: sales
dataProduct: customer_analytics
team:
  dataOwner: sales-analytics-team@example.com
  seniorManager: vp-analytics@example.com
  dataSteward: data-steward@example.com

schema:
  name: silver_sales.customer_orders_summary
  table: customer_orders_summary
  format: delta
  description: Customer order summary aggregated from bronze layer
  properties:
    - name: customer_id
      type: bigint
      description: Unique customer identifier
      isPrimaryKey: true
      isNullable: false

    - name: customer_name
      type: string
      description: Customer full name
      isNullable: false

    - name: total_orders
      type: bigint
      description: Total number of orders
      isNullable: false

    - name: total_amount
      type: decimal(18,2)
      description: Total order amount
      isNullable: false

    - name: avg_order_value
      type: decimal(18,2)
      description: Average order value
      isNullable: false

    - name: first_order_date
      type: date
      description: Date of first order
      isNullable: true

    - name: last_order_date
      type: date
      description: Date of most recent order
      isNullable: true

customProperties:
  pipelineType: transformation
  writeStrategy: scd2
  softDelete: false

  # SQL transformation (inline)
  transformationSql: |
    SELECT
      c.customer_id,
      c.customer_name,
      COUNT(o.order_id) as total_orders,
      SUM(o.order_total) as total_amount,
      AVG(o.order_total) as avg_order_value,
      MIN(o.order_date) as first_order_date,
      MAX(o.order_date) as last_order_date
    FROM bronze_sales.customers c
    LEFT JOIN bronze_sales.orders o
      ON c.customer_id = o.customer_id
    WHERE c.is_active = true
    GROUP BY c.customer_id, c.customer_name

quality:
  cleansing:
    - column: customer_name
      rule: trim

  validation:
    - column: total_orders
      rule: not_null
      severity: error

    - column: total_amount
      rule: min
      value: 0
      severity: error

    - column: customer_id
      rule: unique
      severity: error
